### ISSUE TITLE
unclear/wrong argument description of uLTRA align in help

### ISSUE THREAD

**Issue by MatthiasLienhard** [ksahlin/ultra#1]
Thank you for developing this tool, I think you are approaching an important issue for long read transcriptome sequencing. 

The options and prameters of uLTRA align are somewhat unclear:
`uLTRA align --help` the positional arguments are described as follows:
```
positional arguments:
  ref                   Path to fasta file with a nucleotide sequence (e.g., gene locus) to simulate isoforms from.
  reads                 Path to fasta file with a nucleotide sequence (e.g., gene locus) to simulate isoforms from.
  outfolder             Path to fasta file with a nucleotide sequence (e.g., gene locus) to simulate isoforms from.
```
E.g. all arguments have the same description, which does not really fit to any of them. 
Also, by default, it seems as the files produced by uLTRA index have to be in the "outfolder", so they need to be copied for each processed samples. Is there a way to specify the "index" folder? Further, the final output is "reads.sam". I was looking for a way to provide an sample specific output path and file. Also, uLTRA align seems to produce a lot of temporary files. Is there a reason to keep them? Could you add an option that they get deleted.

**Comment by ksahlin** [comment]
Thank you for reporting! I will try to fix all this asap (hopefully over the weekend).

I will implement: 
1. A parameter `--prefix` to set custom outfile name 
2. A parameter  `--index` for specifying index location.
3. Removal of temporary files
4. Update documentation

**Comment by ksahlin** [comment]
So I implemented the above points 1-4. The new version (v0.0.3.2) is available to install with conda/pip.

For example

```
./uLTRA pipeline test/SIRV_genes.fasta  \
                 /path/to/test/SIRV_genes_C_170612a.gtf \
                 test/reads.fa outfolder \
                --prefix sample_X  \
                --index index
```
Will create and use the index located in folder `index/`, and the final aligned file will be created as `outfolder/sample_X.sam`. Temporary files are also deleted. If they are wished to be kept, this could be specified with option `--keep_temporary_files`.

**Comment by MatthiasLienhard** [comment]
Looks great!

**Comment by MatthiasLienhard** [comment]
Some small notes:

for ultra index
- the difference between "outdir" (Path to output folder) and "index" (Path to where index files will be written to [default is the outfolder path].)  parameters is unclear, as this step should only prepare the index files, right?
- gtf is explained as "Path to **gtf or gtf** file with gene models." Should this be **gff3 file**?
- --disable_infer       "Makes splice creation step much faster. Thes parameter can be set if gene and
                        transcript name fields are provided in gtf file." Isn't this always the case? (and typo "Thes")
