### ISSUE TITLE
Genomes FASTA/GTF files needed to run the evaluation

### ISSUE THREAD

**Issue by FadelBerakdar** [ksahlin/ultra#18]
Hello, 

I have few questions regarding the genome FASTA/GTF files needed in experiment.json file to run Snakefile:

- For human, I am using GENCODE v42 instead of GENCODE v34, and for drosophila release 108 instead of 97. Is this kind of upgrade in versions is not recommended?

- In the experiment.json file,  "TRANSCRIPTOME" : "/home/kris/source/ultra/data/all_transcripts_ENSEMBL.txt", is this the same as GENCODE transcripts.fa ?

- For the SIRV, I am not sure which GTF file I should use, in the data link provided by [Error correction enables use of Oxford Nanopore technology for reference-free transcriptome analysis ](https://www.nature.com/articles/s41467-020-20340-8#data-availability) there are six different GTF files, coud you please indicate which one I should use?

Files links:
Human:
FASTA: https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_42/GRCh38.primary_assembly.genome.fa.gz 
Transcripts FASTA: https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_42/gencode.v42.transcripts.fa.gz
GTF: https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_42/gencode.v42.chr_patch_hapl_scaff.annotation.gtf.gz 

Drosophila melanogaster:
FASTA: https://ftp.ensembl.org/pub/release-108/fasta/drosophila_melanogaster/dna/Drosophila_melanogaster.BDGP6.32.dna.toplevel.fa.gz
GTF: https://ftp.ensembl.org/pub/release-108/gtf/drosophila_melanogaster/Drosophila_melanogaster.BDGP6.32.108.gtf.gz

SIRV:
https://www.lexogen.com/wp-content/uploads/2018/08/SIRV_Set1_Lot00141_Sequences_170612a-ZIP.zip 

Thank you ~ 
Fadel

**Comment by ksahlin** [comment]
Hi @FadelBerakdar 

> For human, I am using GENCODE v42 instead of GENCODE v34, and for drosophila release 108 instead of 97. Is this kind of upgrade in versions is not recommended?

I don't know what the updates are, but if its improved annotations, it should be fine. uLTRA is not dependent on any specific version.

> In the experiment.json file, "TRANSCRIPTOME" : "/home/kris/source/ultra/data/all_transcripts_ENSEMBL.txt", is this the same as GENCODE transcripts.fa ?

No, those are ENSEMBL biomart transcripts. You can ignore those. The relevant annotation we used are in https://github.com/ksahlin/ultra/blob/master/evaluation/Snakefile#L219  (those specific annotation versions should be given in the paper; v34 and release 97)


> For the SIRV, I am not sure which GTF file I should use,

Please use the `SIRV_isoforms_Lot00141_multi-fasta-annotation_C_170612a.gtf`. The 'C' stands for complete annotation. I and stands for incomplete and O stands for overannotated.

**Comment by FadelBerakdar** [comment]
Hi @ksahlin 

Thank you for your respsone. 
The config['TRANSCRIPTOME'] is used by the snakefile in https://github.com/ksahlin/ultra/blob/master/evaluation/Snakefile#L108 and is passed to simulate_reads.py which I guess expects an argument **sequence_material** in fasta format? as in https://github.com/ksahlin/ultra/blob/master/evaluation/simulate_reads.py#L152 

My assumption is that argment is a FASTA file contains the cDNA sequences that are relvant to the GENCODE human geneome ? kindly clearify 

Thank you, 
Fadel

**Comment by ksahlin** [comment]
Ah right! We used the ensemble biomart transcripts (cDNA) obtained from the biomart ensemble webpage to simulate FSM and NIC reads. (the simulated data in our benchmarks).

> sequence_material in fasta format?

yes, the  ensemble biomart transcripts (cDNA)  in fasta format

> My assumption is that argment is a FASTA file contains the cDNA sequences that are relvant to the GENCODE human geneome ? 

The ensemble biomart transcripts are relevant to simulate reads.

**Comment by FadelBerakdar** [comment]
Awesome, thank you for your prompt responses. I could simulate the three datasets.
