### ISSUE TITLE
KeyError when running test pipeline

### ISSUE THREAD

**Issue by DrOllyGomez** [ksahlin/ultra#5]
Hi folks. Superkeen to give ultra a go... looks v cool and will solve some problems.

I've encountered an error running the test package, straight after what I think is a successful, but nonstandard code install.

Here's the observed error to start with:

$ uLTRA pipeline /home/mike.harbour/.virtualenvs/ultra/test/SIRV_genes.fasta /home/mike.harbour/.virtualenvs/ultra/test/SIRV_genes_C_170612a.gtf /home/mike.harbour/.virtualenvs/ultra/test/reads.fa ~/Desktop/ultratest/
Traceback (most recent call last):
  File "/home/mike.harbour/.virtualenvs/ultra/bin/uLTRA", line 648, in <module>
    prep_splicing(args, refs_lengths)
  File "/home/mike.harbour/.virtualenvs/ultra/bin/uLTRA", line 82, in prep_splicing
    max_intron_chr, exon_choordinates_to_id, chr_to_id, id_to_chr = augmented_gene.create_graph_from_exon_parts(db, args.flank_size, args.small_exon_threshold, args.min_segm, refs_lengths)
  File "/home/mike.harbour/.virtualenvs/ultra/lib/python3.6/site-packages/modules/create_augmented_gene.py", line 323, in create_graph_from_exon_parts
    exon_gene_ids = exon.attributes["gene_id"] # is a list of strings
  File "/home/mike.harbour/.virtualenvs/ultra/lib/python3.6/site-packages/gffutils/attributes.py", line 63, in __getitem__
    v = self._d[k]
KeyError: 'gene_id'

I am a virtualenv user rather than a conda user, so as I mentioned, my install was not quite as explained in your github notes, but atm I dont believe there's a problem. Just in case, I'll run through what i did:
1) made new virtual environment, with python at 3.6
2) went into environment, used pip install ultra-bioinformatics. all went well.
3) got the slaMEM and minimap2 dependencies installed and demonstrated.
4) put the uLTRA executable in the PATH and demonstrated it working
5) downloaded the three test files into a testfolder (see the call above)
6) issued call above and received error above.

More than very grateful for any help you can give. Hope I havent goofed.
Best
Mike

**Comment by DrOllyGomez** [comment]
ooh, wait...sorry, I have goofed. my reads file is corrupted. Please ignore this issue for now... I will post again when I've got the correct, working files and passed the test
apologies
Mike

**Comment by DrOllyGomez** [comment]
all is well!
(at least, I need to get the mumMER software working now to get around the slaMEM bug that you outline in your notes :)
thanks, closing this "non-issue" apologies again!
Mike

**Comment by ksahlin** [comment]
Okay, thanks! Let me know if you run into other troubles. I'm just back from vacation and will be more responsive from now.
